export const LINKEDIN_URL = process.env.GATSBY_LINKEDIN_URL || ''
export const GITHUB_URL = process.env.GATSBY_GITHUB_URL || ''
export const FACEBOOK_URL = process.env.GATSBY_FACEBOOK_URL || ''
export const PUBLIC_EMAIL = process.env.GATSBY_PUBLIC_EMAIL || ''
export const GITREPO_URL = process.env.GATSBY_GITREPO_URL || ''
export const SHOW_DB_BUTTON = process.env.GATSBY_SHOW_DB_BUTTON || ''
